# Jekyll 配置文件
title: "Yim's Kitchen"
description: "Yim和他的小伙伴在2610的创作记录！"
url: "https://nozomi209.github.io"
baseurl: "/yimskitchen"

# 作者信息
author:
  name: "Yim"
  email: ""

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - .gitignore

# 集合：食谱
collections:
  recipes:
    output: true
    permalink: /recipes/:name/

# 默认值
defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipe"
      author: "Yi"

# 分页
paginate: 10
paginate_path: "/page:num/"

